misc update

diff --git a/.github/workflows/sync.yaml b/.github/workflows/sync.yaml
--- a/.github/workflows/sync.yaml
+++ b/.github/workflows/sync.yaml
@@ -1,39 +1,39 @@
 name: Upstream Sync
 
 permissions:
-  contents: write
+    contents: write
 
 on:
-  schedule:
-    - cron: "0 0 * * *" # every day
-  workflow_dispatch:
+    schedule:
+        - cron: '0 0 * * *' # every day
+    workflow_dispatch:
 
 jobs:
-  sync_latest_from_upstream:
-    name: Sync latest commits from upstream repo
-    runs-on: ubuntu-latest
-    if: ${{ github.event.repository.fork }}
+    sync_latest_from_upstream:
+        name: Sync latest commits from upstream repo
+        runs-on: ubuntu-latest
+        if: ${{ github.event.repository.fork }}
 
-    steps:
-      # Step 1: run a standard checkout action
-      - name: Checkout target repo
-        uses: actions/checkout@v4
+        steps:
+            # Step 1: run a standard checkout action
+            - name: Checkout target repo
+              uses: actions/checkout@v4
 
-      # Step 2: run the sync action
-      - name: Sync upstream changes
-        id: sync
-        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
-        with:
-          upstream_sync_repo: glidea/claude-worker-proxy
-          upstream_sync_branch: main
-          target_sync_branch: main
-          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
+            # Step 2: run the sync action
+            - name: Sync upstream changes
+              id: sync
+              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+              with:
+                  upstream_sync_repo: glidea/claude-worker-proxy
+                  upstream_sync_branch: main
+                  target_sync_branch: main
+                  target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
 
-          # Set test_mode true to run tests instead of the true action!!
-          test_mode: false
+                  # Set test_mode true to run tests instead of the true action!!
+                  test_mode: false
 
-      - name: Sync check
-        if: failure()
-        run: |
-          echo "[Error] Please manually sync with upstream to resolve the conflicts."
-          exit 1
+            - name: Sync check
+              if: failure()
+              run: |
+                  echo "[Error] Please manually sync with upstream to resolve the conflicts."
+                  exit 1
